### ISSUE TITLE
Turn this repo into a template

### ISSUE THREAD

**Issue by romdim** [nirmaoz/svelte-component-library-template#4]
You can turn this repo into a template as is the case with https://github.com/sveltejs/component-template through the settings.

**Comment by romdim** [comment]
Btw, based on your template, I created another using typescript [here](https://github.com/romdim/svelte-component-template)

(You can also publish your storybook docs for a demo on github pages as I did, let me know if you need any help)

**Comment by maoznir** [comment]
Hi @romdim first of all thanks for the mention in your repo!
and thanks for these great suggestions, i'll handle it soon

**Comment by nirmaoz** [comment]
Hi @romdim, first of all thanks for the mention in your repo!
and thanks for these great suggestions, i'll handle it soon.
